### ISSUE TITLE
DictField, ListField is removed from djongo, error in serializers.py 

### ISSUE THREAD

**Issue by oraix** [SomeoneInParticular/rest_meets_djongo#3]
DictField, ListField is removed from djongo.models.fields, and cause error in serializers.py 

line# 106:
         djm_fields.DictField: drf_fields.DictField,
         djm_fields.ListField: drf_fields.ListField,

**Comment by SomeoneInParticular** [comment]
Thanks for the heads up; I'll patch it ASAP

**Comment by SomeoneInParticular** [comment]
I've made the changes; however, their is a major bug in Djongo which prevents me from testing the changes with my unit tests (see Issue #404 in Djongo for details). So I can confirm nothing major has broken in the process, I've currently only released these changes as an alpha (version 0.0.13a0) for now; the full "tested" release will come out once the Djongo bug is patched.

**Comment by oraix** [comment]
Thanks for your quick response and modification. Rest_meets_djongo is great! 
[#404](https://github.com/nesdis/djongo/issues/404) was fixed already.
But there are still many other issues in latest version of Djongo. 
It's seems Djongo 1.2.38 with rest_meets_djongo 0.0.11 is the most stable combination.

I submit another issue in Djongo, do you have any suggestion to resolve it?
https://github.com/nesdis/djongo/issues/407

**Comment by SomeoneInParticular** [comment]
#404 is fixed by reverting to an older djongo version; still, that version still lacked Dict and List fields, and reverting my packages test suite to use that version (1.3.1) showed all tests passed (sans a slight slip up I made editing the test cases to reflect the change, anyways). So, as far as I can tell, rest-meets-djongo is now stable for use with djongo v.1.3.1.

With regards to your issue on Djongo's end, I'll look into it shortly and see if I can figure out the source of the problem. Apologies for the delay; life just threw something at me I need to deal with first.

**Comment by SomeoneInParticular** [comment]
So, it appears Djongo has (still) not fixed its release for 1.3.2; that seems most likely to be the culprit (and your issue on that repo appears to cover it attempting to be fixed). Every test that I throw at it works as intended with 1.3.1, so I'm going to close this issue until djongo 1.3.2 is fixed (or djongo 1.3.3 releases) and I can test again. I'll re-open this if this issue crops up again.
